import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Head } from "next/document";
import Link from "next/link";

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
   <header className="tracking-in-expand h-[50px]  flex justify-between p-[15px] md:text-[30px] md:h-[80px]">

    <Link href={"/"} className=" active text-white uppercase font-bold hover:underline">Home</Link>
    <Link href={"./Iphon"} className=" active text-white uppercase font-bold hover:underline">Iphones</Link>
    <Link href={"./Earbuds"} className=" active text-white uppercase font-bold hover:underline ">Earbuds</Link>
    <Link href={"./Watch"} className=" active text-white uppercase font-bold hover:underline hidden sm:block md:block">Watches</Link>
    <Link href={"./Keychain"} className="  active text-white uppercase font-bold hover:underline hidden sm:block md:block ">Keychain</Link>

    </header>
        {children}
        
    <footer className="h-[50px] border-t-white border-solid border-[30px] border-b-0 border-l-0 border-r-0 text-white  p-[10px] mb-[20px] 
     text-center text-[20px] sm:text-[30px] md:text-[30px] md:h-[70px] ">
        <p>&copy; 2024 <span className="text-yellow-500">FAIZA NAAZ</span>.</p>
        <p>Thank you for visiting our website!</p>
    </footer>  
      </body>
    </html>
  );
}
