import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className="text-[20px]  font-bold flex flex-col items-center justify-center  " suppressContentEditableWarning>
        {/* suppressContentEditableWarning sy falto ki jo errors aty hen wo nhi deta ye */}
        {children}
      </body>
    </html>
  );
}
